name: ernesto
services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/api
    env_file:
      - .env
    depends_on:
      - db

  api-dev:
    build: .
    ports:
      - "8081:8081"
    volumes:
      # mount monorepo's root folder (we need access to the .git folder)
      - ../..:/ernesto:cached
    env_file:
      - .env
    depends_on:
      - db
    # Install dev requirements and start an interactive shell
    command: sleep infinity
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ernesto
    ports:
      - "5432:5432"

volumes:
  postgres_data: 