[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | app/migrations
)/
'''

[tool.ruff]
line-length = 88
target-version = "py39"
exclude = [
    "app/migrations/",
]

[tool.ruff.lint]
select = ["E", "F", "I", "ANN", "D"]
ignore = ["E203", "E501", "D203", "D213"]
fixable = ["ALL"]

[tool.pytest.ini_options]
# Configure pytest warning handling
filterwarnings = [
    "error",  # Turn warnings into errors by default
    # Allow expected configuration warnings in development/testing
    "ignore:.*Using default SECRET_KEY in development.*:UserWarning",
    # Allow general configuration warnings during testing
    "ignore:.*Configuration warning.*:UserWarning",
    # Ignore ResourceWarning from unclosed log files in tests
    "ignore:unclosed file.*:ResourceWarning",
    # Ignore PytestUnraisableExceptionWarning from logging handlers
    "ignore:Exception ignored in.*FileIO.*:pytest.PytestUnraisableExceptionWarning",
]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "-v",
    "--strict-markers",
    "--strict-config",
    "--tb=short",
] 