name: ernesto
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/api
    env_file:
      - ./api/.env
    depends_on:
      - db
    command: flask run --host=0.0.0.0 --port=8080

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ernesto
    ports:
      - "5432:5432"

volumes:
  postgres_data: 