name: ernesto
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/api
    env_file:
      - ./api/.env
    depends_on:
      - db

  api-dev:
    build: ./api
    ports:
      - "8081:8081"
    volumes:
      # mount monorepo's root folder (we need access to the .git folder)
      - ..:/ernesto:cached
    env_file:
      - ./api/.env
    depends_on:
      - db
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ernesto
    ports:
      - "5432:5432"

volumes:
  postgres_data: 