"""Initial Flask-Alembic setup

Revision ID: 1748269708
Revises: 
Create Date: 2025-05-26 14:28:28.087431

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "1748269708"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ("default",)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
